### PR TITLE
Fixed issue #1

### PR DESCRIPTION
**Pull request by davidwdan**

### CODE REVIEW

**Comment by clue** [comment]
Thanks for your PR! :+1: 

Looks like the docs suggest one should simply call `readline_callback_handler_install()` again in order to redraw the prompt and the `readline_callback_handler_remove()` call can be avoided: http://php.net/manual/en/function.readline-callback-handler-install.php

I'd love to get this in, can you confirm this / update your PR and fix the indentation? :shipit:

**Comment by clue** [comment]
Ping @davidwdan, any updates? :+1:

**Comment by davidwdan** [comment]
@clue sorry, I missed your comment.  I'll take a look at this later tonight.

**Comment by davidwdan** [comment]
ping @clue

**Comment by clue** [comment]
Unfortunately, the new array syntax break compatibility with PHP 5.3 (yeah, I know…).

Can you revert this to use the explicit array syntax instead and squash all changes into a single commit? :shipit:

**Comment by davidwdan** [comment]
done

**Comment by clue** [comment]
Much appreciated! :shipit:

**Pull request merged**
